### ISSUE TITLE
Exception in manual detection mode

### ISSUE THREAD

**Issue by jfisteus** [jfisteus/eyegrade#113]
I got this when I clicked on the take snapshot button and clicked on a corner of the answer box:

```
Traceback (most recent call last):
  File "eyegrade/eyegrade/qtgui/widgets.py", line 464, in mousePressEvent
    self.mouse_listener((event.x(), event.y()))
  File "eyegrade/eyegrade/eyegrade.py", line 686, in _mouse_pressed
    self._mouse_pressed_change_answer(point)
  File "eyegrade/eyegrade/eyegrade.py", line 691, in _mouse_pressed_change_answer
    question, answer = self.exam.capture.get_cell_clicked(point)
  File "eyegrade/eyegrade/capture.py", line 124, in get_cell_clicked
    for i, cells in enumerate(self.answer_cells):
TypeError: 'NoneType' object is not iterable
```

**Comment by jfisteus** [comment]
See also issue #80 when dealing with this one.
