### ISSUE TITLE
Unicode error on Windows

### ISSUE THREAD

**Issue by jfisteus** [jfisteus/eyegrade#115]
The user name has a non-ascii character and that seems to provoke the error:

```
C:\Users\Jesús\AppData\Local\Eyegrade>eyegrade-create -h
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "eyegrade\create_exam.py", line 25, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "eyegrade\utils.py", line 86, in <module>
  File "eyegrade\utils.py", line 69, in _read_config
  File "ntpath.py", line 311, in expanduser
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfa in position 12: ordinal not in range(128)
eyegrade-create returned -1
```

**Comment by jfisteus** [comment]
I've tested commit 73b90ec. It works as expected and solves the issue.
