### ISSUE TITLE
Fallback to PyQt4 breaks the pyinstaller build

### ISSUE THREAD

**Issue by jfisteus** [jfisteus/eyegrade#120]
When eyegrade is built with PyInstaller it seems that both PyQt4 and PyQt5 get loaded. This has to do with commit a3b4b19c93ad94cc8, which makes eyegrade fall back to PyQt4 when PyQt5 can't be loaded.

```
Traceback (most recent call last):
  File "<string>", line 61, in <module>
  File "/tmp/pip-build-Y61aCK/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 546, in load_module
RuntimeError: the PyQt5.QtCore and PyQt4.QtCore modules both wrap the QObject class
pyi_rth_qt5 returned -1
```

Perhaps the best option is ditching this fallback code, at least for building the PyInstaller binary.

**Comment by jfisteus** [comment]
PyQt4 support has been removed as of commit 4cffb0fdf608
