### ISSUE TITLE
Exception related to unicode

### ISSUE THREAD

**Issue by jfisteus** [jfisteus/eyegrade#121]
Exception at the end of the new session dialog.

(On branch development, commit a3b4b19c93ad94cc828600dc4134ea484adab9d6)

Traceback (most recent call last):
  File "eyegrade/eyegrade/eyegrade.py", line 410, in _new_session
    values = self.interface.dialog_new_session()
  File "eyegrade/qtgui/gui.py", line 798, in dialog_new_session
    return dialog.values()
  File "eyegrade/qtgui/wizards.py", line 881, in values
    values['id_list_files'] = self.student_id_files()
  File "eyegrade/qtgui/wizards.py", line 874, in student_id_files
    return self.files_w.get_files()
  File "eyegrade/qtgui/widgets.py", line 446, in get_files
    files.append(unicode(model.data(index).toString()))
AttributeError: 'unicode' object has no attribute 'toString'

**Comment by cnt5bs** [comment]
Hi! Any news about this bug?

**Comment by jfisteus** [comment]
No, I'm sorry. I focused on publishing version 0.7 in July (which is not affected by this bug). I hope to have some time in september to fix this one.

**Comment by cnt5bs** [comment]
Thank you. I'll wait for the next version of your very useful tool. Regards.
