### ISSUE TITLE
Exception after a student was added manually

### ISSUE THREAD

**Issue by jfisteus** [jfisteus/eyegrade#155]
After adding a new student manually to the list, the following exception happened just when grading the next exam:

```
Traceback (most recent call last):
  File "eyegrade/git/eyegrade/eyegrade.py", line 320, in _after_image_detection
    exam = self._process_capture(detector)
  File "eyegrade/git/eyegrade/eyegrade.py", line 434, in _process_capture
    sessiondb=self.sessiondb,
  File "eyegrade/git/eyegrade/exams.py", line 50, in __init__
    rank = self.rank_students()
  File "eyegrade/git/eyegrade/exams.py", line 87, in rank_students
    for s in self.student_listings.iter_students()
  File "eyegrade/git/eyegrade/exams.py", line 88, in <listcomp>
    if s.group_id > 0
  File "eyegrade/git/eyegrade/exams.py", line 157, in _id_rank
    rank += scores[i][int(digit)]
IndexError: list index out of range
```

**Comment by jfisteus** [comment]
The problem was that the student id was mistakenly inserted with one extra digit. This case needs to be checked in order to avoid such a crash. An error message should be shown to the user.
