### ISSUE TITLE
Exception when removing an exam capture while grading

### ISSUE THREAD

**Issue by jfisteus** [jfisteus/eyegrade#161]
Traceback (most recent call last):
  File "git/eyegrade/eyegrade.py", line 625, in _action_discard
    self.interface.remove_exam(self.exam)
  File "git/eyegrade/qtgui/gui.py", line 722, in remove_exam
    self.window.exams_view.remove_exam(exam)
  File "git/eyegrade/qtgui/examsview.py", line 95, in remove_exam
    pos = self.exams.index(exam)
          ^^^^^^^^^^^^^^^^^^^^^^
ValueError: <eyegrade.exams.Exam object at 0x7f06529ef450> is not in list

Eyegrade version: commit fa46beea9dee

**Comment by jfisteus** [comment]
Duplicate of issue #127.

**Comment by jfisteus** [comment]
The problem might be clicking on the discard button more than once. The second listener would run with the exam already removed.

It might be better to check that the exam is still in `self.exams`, and remove it only if it is.
