### ISSUE TITLE
numpy version fix

### ISSUE THREAD

**Issue by anmaped** [jfisteus/eyegrade#170]
Please set the numpy version or fix it for numpy2, otherwise pypi (pipx) is broken.

```
numpy==1.26.4
```

```
RuntimeError: module compiled against ABI version 0x1000009 but this version of numpy is 0x2000000
Traceback (most recent call last):
  File "/home/dematos/Downloads/eyegrade-0.9-bin-linux/venv/bin/eyegrade", line 5, in <module>
    from eyegrade.eyegrade import main
  File "/home/dematos/Downloads/eyegrade-0.9-bin-linux/venv/lib64/python3.12/site-packages/eyegrade/eyegrade.py", line 29, in <module>
    from . import detection
  File "/home/dematos/Downloads/eyegrade-0.9-bin-linux/venv/lib64/python3.12/site-packages/eyegrade/detection.py", line 23, in <module>
    import cv2
  File "/home/dematos/Downloads/eyegrade-0.9-bin-linux/venv/lib64/python3.12/site-packages/cv2/__init__.py", line 8, in <module>
    from .cv2 import *
ImportError: numpy.core.multiarray failed to import
```

**Comment by jfisteus** [comment]
Thanks for your report, @anmaped. Could you please detail what was the installation process that failed? Was it pipx install eyegrade or pip install eyegrade?

**Comment by anmaped** [comment]
> Thanks for your report, @anmaped. Could you please detail what was the installation process that failed? Was it pipx install eyegrade or pip install eyegrade?

Both, also tried pip with venv.

**Comment by jfisteus** [comment]
The problem was due to eyegrade 0.9 pinning an opencv version but not a numpy version. This made numpy 2.x be installed, which is incompatible with the pinned opencv version.

I've uploaded version 0.9.1 to PyPI to fix the problem. This new version pins recent versions of both opencv and numpy. I've checked that it can again be installed and run with both pip and pipx. As a side effect, Python 3.10, or a later version, is now required.

Thanks again for your report.

Note: I'm not releasing Windows/Linux binaries for 0.9.1 since the binaries for 0.9 still work (they bundle a set of dependencies that work together, from the time they were released) and there isn't any code change between the two versions. The problem affected the version on PyPI only.
