### ISSUE TITLE
Bug in Windows when setting scores

### ISSUE THREAD

**Issue by jfisteus** [jfisteus/eyegrade#96]
In Windows, setting the exam scores with the same score for all the questions, computing default scores and then finishing the dialog provokes the following error:

```
Traceback (most recent call last):
  File "C:\eyegrade\eyegrade\qtgui\wizards.py", line 226, in validatePage
    elif self._consolidate_base_scores():
  File "C:\eyegrade\eyegrade\qtgui\wizards.py", line 343, in _consolidate_base_s
cores
    same_weights=same_weights)
  File "C:\eyegrade\eyegrade\utils.py", line 1032, in set_base_scores
    self.set_equal_scores(model)
  File "C:\eyegrade\eyegrade\utils.py", line 1046, in set_equal_scores
    self._set_question_scores_internal(model, scores)
  File "C:\eyegrade\eyegrade\utils.py", line 1129, in _set_question_scores_inter
nal
    raise ValueError('Scores for all models must be equal '
ValueError: Scores for all models must be equal but their order
```

**Comment by jfisteus** [comment]
The problem happens also in Linux. It is similar to the problem fixed in commit cd81192b0478f6d8e85208d9b26ba069f3e7acd1.
